# ==============================================================================
# Zenith V2 Master Configuration
#
# This file is the central control panel for the entire application.
# All strategy parameters, risk settings, and connection details are defined here.
# ==============================================================================

# ------------------------------------------------------------------------------
# Strategy Parameters
# ------------------------------------------------------------------------------
[strategies]

# Parameters for the Triple Moving Average Crossover strategy.
# - Fast/Slow MA for the signal.
# - Trend Filter MA to ensure we only trade with the larger trend.
[strategies.ma_crossover]
ma_fast_period = 10
ma_slow_period = 50
trend_filter_period = 200

# Parameters for the SuperTrend strategy with an ADX filter.
# - SuperTrend is calculated from ATR.
# - ADX filter requires trend strength to be above a threshold before entering.
[strategies.super_trend]
atr_period = 14
atr_multiplier = 3.0
adx_threshold = 25.0
adx_period = 14

# Parameters for the Probabilistic Mean Reversion strategy.
# - A signal requires price outside Bollinger Bands, RSI in overbought/sold,
#   AND ADX below a threshold (confirming a ranging market).
[strategies.prob_reversion]
bb_period = 20
bb_std_dev = 2.0
rsi_period = 14
rsi_oversold = 30.0
rsi_overbought = 70.0
adx_threshold = 20.0
adx_period = 14

# Parameters for Funding Rate Arbitrage.
[strategies.funding_rate_arb]
target_rate_threshold = 0.001  # e.g., 0.1%
basis_safety_threshold = 0.005 # e.g., 0.5% basis between spot and perp