# ==============================================================================
# Zenith V2 Master Configuration
#
# This file is the central control panel for the entire application.
# All strategy parameters, risk settings, and connection details are defined here.
# ==============================================================================

# ------------------------------------------------------------------------------
# API Configuration
#
# API keys for different environments. These can be overridden via environment variables.
# ------------------------------------------------------------------------------
[api]
binance_api_key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
binance_api_secret = "9ae595bb00812a75a3f1f43932599eba8177d668690a664eaea5c0f0071b9431"
# Testnet API keys (for testing)
[api.testnet]
binance_api_key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
secret = "9ae595bb00812a75a3f1f43932599eba8177d668690a664eaea5c0f0071b9431"

# Production API keys (for live trading)
[api.production]
binance_api_key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
key = "31fbf16926ce01bfbf2dad27e1c087fc89749d9c1ea8d5c45db3c4c99620c920"
secret = "9ae595bb00812a75a3f1f43932599eba8177d668690a664eaea5c0f0071b9431"

# ------------------------------------------------------------------------------
# Default Backtest Configuration
#
# Parameters for the `single-run` command.
# ------------------------------------------------------------------------------
[backtest]
symbol = "BNBUSDT"
interval = "15m"
initial_capital = 1000.0
start_date = "2025-01-01"
end_date = "2025-06-30"

# ------------------------------------------------------------------------------
# Simulation Engine Parameters
#
# These rules govern the behavior of the backtester's virtual exchange.
# ------------------------------------------------------------------------------
[simulation]
# Taker Fee: The fee charged for market orders. (e.g., Binance Futures is 0.04%)
taker_fee_pct = 0.0004

# Slippage: A simple model assuming slippage is a percentage of the bar's range.
# 0.1 means we assume a 10% worse fill from the close price, in the direction of the bar's range.
slippage_pct = 0.1

# ------------------------------------------------------------------------------
# Risk Management
#
# These rules govern how individual trades are sized.
# ------------------------------------------------------------------------------
[risk_management]
# The fraction of the total portfolio equity to risk per trade.
# 0.005 means 0.5% of equity will be at risk on any given trade.
risk_per_trade_pct = 0.005

# The distance to the stop-loss, used for calculating position size.
# 0.01 means the stop-loss is assumed to be 1% away from the entry price.
stop_loss_pct = 0.01

# ------------------------------------------------------------------------------
# Strategy Parameters
# ------------------------------------------------------------------------------
[strategies]

# Parameters for the Triple Moving Average Crossover strategy.
# - Fast/Slow MA for the signal.
# - Trend Filter MA to ensure we only trade with the larger trend.
[strategies.ma_crossover]
ma_fast_period = 20
ma_slow_period = 30
trend_filter_period = 50

# Parameters for the SuperTrend strategy with an ADX filter.
# - SuperTrend is calculated from ATR.
# - ADX filter requires trend strength to be above a threshold before entering.
[strategies.super_trend]
atr_period = 14
atr_multiplier = 3.0
adx_threshold = 25.0
adx_period = 14

# Parameters for the Probabilistic Mean Reversion strategy.
# - A signal requires price outside Bollinger Bands, RSI in overbought/sold,
#   AND ADX below a threshold (confirming a ranging market).
[strategies.prob_reversion]
bb_period = 20
bb_std_dev = 2.0
rsi_period = 14
rsi_oversold = 30.0
rsi_overbought = 70.0
adx_threshold = 20.0
adx_period = 14

# Parameters for Funding Rate Arbitrage.
[strategies.funding_rate_arb]
target_rate_threshold = 0.001  # e.g., 0.1%
basis_safety_threshold = 0.005 # e.g., 0.5% basis between spot and perp