# ==============================================================================
# Zenith Optimizer - SuperTrend Strategy Example
# ==============================================================================
# 
# This is an example configuration for optimizing the SuperTrend strategy.
# Copy this file and modify the strategy_id and parameter_space as needed.

# --- Base Settings ---
[base_config]
strategy_id = "SuperTrend"  # Changed from MACrossover to SuperTrend
symbol = "BTCUSDT"
interval = "1m"

# --- SuperTrend Strategy Parameters ---
[parameter_space]
# ATR period for volatility calculation
atr_period = { start = 10, end = 30, step = 2 }
# ATR multiplier for SuperTrend calculation
atr_multiplier = { start = 2.0, end = 5.0, step = 0.5 }
# ADX threshold for trend strength filter
adx_threshold = { start = 20, end = 40, step = 5 }
# ADX period for trend strength calculation
adx_period = { start = 10, end = 20, step = 2 }

# ==============================================================================
# Analysis & Ranking Configuration
# ==============================================================================
[analysis]

# --- Filters ---
[analysis.filters]
min_total_trades = 2
max_drawdown_pct = 70.0

# --- Scoring Weights ---
[analysis.scoring_weights]
weight_profit_factor = 0.3
weight_calmar_ratio = 0.5
weight_avg_win_loss_ratio = 0.2

# ==============================================================================
# Walk-Forward Optimization (Optional)
# ==============================================================================
# Uncomment to enable WFO
# [wfo]
# in_sample_weeks = 8
# out_of_sample_weeks = 2 